#!/usr/bin/env bash

subs=("www" "lb-01" "web-01" "web-02")

dns_details () {
	if [ -z "$1" ]
	then
		return
	fi

	if [ -z "$2" ]
	then
		for sub in "${subs[@]}"; do
			rec=$(dig "$sub"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
			ip=$(dig "$sub"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
			echo "The subdomain $sub is a $rec record and points to $ip"
		done
	else
		rec=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
		ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
		echo "The subdomain $2 is a $rec record and points to $ip"
	fi
}

dns_details "$1" "$2"
