#!/usr/bin/env bash
# Redirection

redirection_cmd="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/server_name _;/a $redirection_cmd" /etc/nginx/sites-available/default
sudo service nginx reload
