#!/usr/bin/env bash
# Redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server/a \trewrite ^/redirect_me https://github.com permane
nt;" /etc/nginx/sites-available/default
sudo service nginx reload
