#!/usr/bin/env bash
# Redirection

redirection_cmd="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo sed -i "/server_name _;/a $redirection_cmd" ed
