#!/usr/bin/env bash
# Redirection & Custom 404 page

redirection_cmd="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
not_found="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

# Install and setup nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

# Redirect /redirect_me to another url
sed -i "/server_name _;/a $redirection_cmd" /etc/nginx/sites-available/default

# Setup custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "/server_name _;/a $not_found" /etc/nginx/sites-enabled/default

# Setup custom http response header
sed -i "/server_name _;/a \\\n\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default

# Restart nginx server
service nginx restart
