#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it’s executed on

ifconfig_res=$(ifconfig)

my_ipvs=$(echo "$ifconfig_res" | grep -Eo 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')

echo "$my_ipvs" | cut -f 2 -d ' '
