#!/usr/bin/env bash
# Run nginx as nginx

sed -i 's/^user .*;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod u+r /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
